###

GET http://localhost:3000/student

###

GET http://localhost:3000/student?name=John3

###

GET http://localhost:3000/student/02221233022


###

POST http://localhost:3000/student
Content-Type: application/json

{
    "name": "John 444",
    "age": 20,
    "_id": "02221233022"
}

###

PUT http://localhost:3000/student


###

DELETE http://localhost:3000/student

###

GET http://localhost:3000/post


###


POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "email": "test@gmail.com",
    "password": "123456",
    "full_name": "Shoham Moyal",
    "profile_picture": "null",
    "gender": "Male",
    "student": {
        "year": 4,
        "faculty": "Software Engineering",
        "posts": []
        }
}



// main user 
###


POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "email": "moyal.shoham@gmail.com",
    "password": "123456",
    "full_name": "Shoham Moyal",
    "profile_picture": "null",
    "gender": "Male",
    "student": {
        "year": 4,
        "faculty": "Software Engineering",
        "posts": []
        }
}


###

POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "test@gmail.com",
    "password": "123456"
}


###

POST http://localhost:3000/post/upload
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjQwYWZmMTNmNTIxZDZjM2Q1NjkyMTIiLCJpYXQiOjE3MTU1MjE3MjYsImV4cCI6MTcxNTUyNDcyNn0.C_bYVu_YkyHyTmL1ZFJ3gRKLSq6t5FJn1nKCBaeLSfU

{
    "message": "Paam Shnia",
    "image": "stamTmuna.jpg"
}


###

GET http://localhost:3000/post/my/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjQwZDU2NTE0YWM3NmU0MjdmMjA1N2IiLCJpYXQiOjE3MTU1MjQ5ODcsImV4cCI6MTcxNTUyNzk4N30.2QG6hwLApj3o7f2cooj6biMJ1ZU8HKF0wuQebb6bjHA

###

GET http://localhost:3000/post/all/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjQwZDU2NTE0YWM3NmU0MjdmMjA1N2IiLCJpYXQiOjE3MTU1MjQ5ODcsImV4cCI6MTcxNTUyNzk4N30.2QG6hwLApj3o7f2cooj6biMJ1ZU8HKF0wuQebb6bjHA


###

PUT http://localhost:3000/auth/update/6640ff89fde7e78d38022184
Content-Type: application/json

{
    "email": "moyal.shoham@gmail.com",
    "password": "123456",
    "full_name": "Shoham Moyal",
    "profile_picture": "Shoham.jpg",
    "gender": "Male",
    "posts": [],
    "student": "6640ff89fde7e78d38022182"

}


###

DELETE http://localhost:3000/auth/delete/6640ff89fde7e78d38022184