###

GET http://localhost:3000/student

###

GET http://localhost:3000/student?name=John3

###

GET http://localhost:3000/student/02221233022


###

POST http://localhost:3000/student
Content-Type: application/json

{
    "name": "John 444",
    "age": 20,
    "_id": "02221233022"
}

###

PUT http://localhost:3000/student


###

DELETE http://localhost:3000/student

###

GET http://localhost:3000/post


###


POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "email": "test@gmail.com",
    "password": "123456",
    "full_name": "Shoham Moyal",
    "profile_picture": "null",
    "gender": "Male",
    "student": {
        "year": 4,
        "faculty": "Software Engineering",
        "posts": []
        }
}



// main user 
###


POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "email": "moyal@gmail.com",
    "password": "123456",
    "full_name": "Shoham Moyal",
    "profile_picture": "none",
    "gender": "Male",
    "year": 4,
    "faculty": "Software Engineering",
    "posts": []

}


###

POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "moyal@gmail.com",
    "password": "123456"
}

###

POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "S@t.com",
    "password": "12"
}


###

POST http://localhost:3000/post/upload
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjRiNmU3NTUwNDE1ODQwZGZlMmQ2ZjMiLCJpYXQiOjE3MTYyMTk1NzUsImV4cCI6MTcxNjIyMjU3NX0.inPsaDbHiHil6NA0v4gtzqhtMC154bw0KkTYV_cfbBM

{
    "message": "Plizzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz Gadol113",
    "image": "stamTm222una.jpg"
}


###

GET http://localhost:3000/post/my/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjQ2MTk2YzkxMWQ4N2VlNWZlZWEwMjMiLCJpYXQiOjE3MTU4NzAwNzYsImV4cCI6MTcxNTg3MzA3Nn0.A8swsyJZUuY9mQ0mHz-0fCke_8XwrvQYZPM_3t8v92Q


###



GET http://localhost:3000/post/all/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjQ2MTk2YzkxMWQ4N2VlNWZlZWEwMjMiLCJpYXQiOjE3MTU4NzAwNzYsImV4cCI6MTcxNTg3MzA3Nn0.A8swsyJZUuY9mQ0mHz-0fCke_8XwrvQYZPM_3t8v92Q


###

PUT http://localhost:3000/auth/update/6640ff89fde7e78d38022184
Content-Type: application/json

{
    "email": "moyal.shoham@gmail.com",
    "password": "123456",
    "full_name": "Shoham Moyal",
    "profile_picture": "Shoham.jpg",
    "gender": "Male",
    "posts": [],
    "student": "6640ff89fde7e78d38022182"

}


###

DELETE http://localhost:3000/auth/delete/6640ff89fde7e78d38022184



###

PUT http://localhost:3000/post/66420f7d3880c0913be8cd90
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjQyMGY1NDM4ODBjMDkxM2JlOGNkOGIiLCJpYXQiOjE3MTU2MDUzMzUsImV4cCI6MTcxNTYwODMzNX0.FGDIFwkVh8YVI8uJ3H0AvmhGqz0X8pYD2NoJdoKCOzo

{
    "message": "Test Gadol Meod",
    "image": "stamTmuna2.jpg"
}


###

DELETE http://localhost:3000/post/delete/66410b284d540916cdde314c


###


GET http://localhost:3000/auth/logout/66420f543880c0913be8cd8b
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjQyMGY1NDM4ODBjMDkxM2JlOGNkOGIiLCJpYXQiOjE3MTU2MTIzNjUsImV4cCI6MTcxNTYxNTM2NX0.19c0z-z4jVlJ_JnqNwOhvq3NEWd-A47PVYzCqoBv0f8




###

GET http://localhost:3000/auth/user/664c7de07bd5aa49356df60d



###

GET http://localhost:3000/auth/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjRjOGNiOTdhZTUyZTM5ZmRmYmY4NDYiLCJpYXQiOjE3MTYyOTQ5OTAsImV4cCI6MTcxNjI5Nzk5MH0.BRH-WXiVSHR_VsKt6QjdR5clKhkVfOfwknH4wt9Dx3Y
###

PUT http://localhost:3000/auth/update


###

GET http://localhost:3000/post/my/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjRjOGNiOTdhZTUyZTM5ZmRmYmY4NDYiLCJpYXQiOjE3MTYzMDQyMzgsImV4cCI6MTcxNjMwNzIzOH0.VVkc2q8okuKMxRxxMRtawLFiEuguI129ZFWB7GjK960